try {
  let a = 1
  throw e
} catch (e) {
  console.log(a)
} finally {
  console.log(a)
}
